name: Feature Request
description: Template for requesting new features
title: "[Feature Request] Describe the feature"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **As a** [role]  
        **I need** [function]  
        **So that** [benefit]  

  - type: input
    attributes:
      label: Details and Assumptions
      description: "Document what you know about the feature request. Include any assumptions or relevant details."
      placeholder: "Enter details and assumptions here..."

  - type: input
    attributes:
      label: Acceptance Criteria
      description: "Define the acceptance criteria for this feature request using Gherkin syntax."
      placeholder: |
        gherkin
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
