name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Run the job in a Python 3.9 slim container
    container:
      image: python:3.9-slim

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
        volumes:
          - postgres:/var/lib/postgresql/data
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies (with pip and wheel)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for Postgres..."
            sleep 5
          done

      # Run migrations or other database setup (optional)
      - name: Run database migrations
        run: |
          python manage.py migrate

      # Lint the code with flake8
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      # Run tests
      - name: Run tests
        run: |
          pytest

# Define the Docker volume for the Postgres service
volumes:
  postgres:
