name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Run the job in a Python 3.9 slim container
    container:
      image: python:3.9-slim

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
        volumes:
          - postgres:/var/lib/postgresql/data
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (e.g., from requirements.txt or pyproject.toml)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for Postgres..."
            sleep 5
          done

      # Run migrations or other database setup (optional)
      - name: Run database migrations
        run: |
          # Example: Python migration (you can replace with your own commands)
          python manage.py migrate

      # Run tests
      - name: Run tests
        run: |
          # Example for running pytest or another test framework
          pytest

# Define the Docker volume for the Postgres service
volumes:
  postgres:
